import { Agent, Task, LogEntry, Metrics } from '@/types';

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'clow',
    name: 'Clow',
    emoji: '🤖',
    role: 'Copy AI',
    color: '#00BFFF',
    visorColor: '#00F5FF',
    status: 'Trabalhando',
    task: 'Gerando headlines Maio',
    state: 'sitting',
    x: 162, y: 155,
    targetX: 162, targetY: 155,
    walkFrame: 0,
    deskIndex: 0,
    stateTimer: 280,
  },
  {
    id: 'finn',
    name: 'Finn',
    emoji: '📊',
    role: 'Tráfego AI',
    color: '#FF6B00',
    visorColor: '#FF9A40',
    status: 'Analisando dados',
    task: 'Otimizando lances Meta',
    state: 'sitting',
    x: 244, y: 155,
    targetX: 244, targetY: 155,
    walkFrame: 0,
    deskIndex: 1,
    stateTimer: 190,
  },
  {
    id: 'aninha',
    name: 'Aninha',
    emoji: '🌿',
    role: 'Data AI',
    color: '#00CC66',
    visorColor: '#00FF88',
    status: 'Executando tarefa',
    task: 'Relatório semanal leads',
    state: 'sitting',
    x: 326, y: 155,
    targetX: 326, targetY: 155,
    walkFrame: 0,
    deskIndex: 2,
    stateTimer: 240,
  },
  {
    id: 'zezinho',
    name: 'Zezinho',
    emoji: '🎨',
    role: 'Design AI',
    color: '#9B59B6',
    visorColor: '#DD88FF',
    status: 'Em reunião',
    task: 'Aguard. brief criativo',
    state: 'at_coffee',
    x: 190, y: 290,
    targetX: 190, targetY: 290,
    walkFrame: 0,
    deskIndex: 3,
    stateTimer: 120,
  },
  {
    id: 'lala',
    name: 'Lala',
    emoji: '🔍',
    role: 'SEO AI',
    color: '#00B8A9',
    visorColor: '#00F0E0',
    status: 'Trabalhando',
    task: 'Auditando keywords',
    state: 'sitting',
    x: 490, y: 155,
    targetX: 490, targetY: 155,
    walkFrame: 0,
    deskIndex: 4,
    stateTimer: 310,
  },
  {
    id: 'wink',
    name: 'Wink',
    emoji: '⚡',
    role: 'Ops AI',
    color: '#E67E22',
    visorColor: '#F39C12',
    status: 'Em descanso',
    task: 'Processando acordos',
    state: 'on_sofa',
    x: 58, y: 235,
    targetX: 58, targetY: 235,
    walkFrame: 0,
    deskIndex: 5,
    stateTimer: 80,
  },
  {
    id: 'dino',
    name: 'Dino',
    emoji: '🚀',
    role: 'Growth AI',
    color: '#C0392B',
    visorColor: '#FF6B6B',
    status: 'Trabalhando',
    task: 'Consolidando carteira',
    state: 'sitting',
    x: 574, y: 155,
    targetX: 574, targetY: 155,
    walkFrame: 0,
    deskIndex: 5,
    stateTimer: 220,
  },
  {
    id: 'aranha',
    name: 'Aranha',
    emoji: '🕷️',
    role: 'CRM AI',
    color: '#2C3E50',
    visorColor: '#7F8C8D',
    status: 'Executando tarefa',
    task: 'Atualizando CRM leads',
    state: 'chatting',
    x: 230, y: 280,
    targetX: 230, targetY: 280,
    walkFrame: 0,
    deskIndex: 3,
    stateTimer: 160,
  },
];

export const INITIAL_TASKS: Task[] = [
  { id: 't1', title: 'Headline Maio', category: 'COPY', status: 'andamento', agentId: 'clow', priority: 'alta' },
  { id: 't2', title: 'Relatório semanal', category: 'DATA', status: 'andamento', agentId: 'aninha', priority: 'alta' },
  { id: 't3', title: 'Lances Meta Ads', category: 'ADS', status: 'andamento', agentId: 'finn', priority: 'media' },
  { id: 't4', title: 'Brief criativo', category: 'DESIGN', status: 'bloqueado', agentId: 'zezinho', priority: 'alta' },
  { id: 't5', title: 'Gerar boletos lote', category: 'OPS', status: 'andamento', agentId: 'wink', priority: 'alta' },
  { id: 't6', title: 'Atualizar CRM', category: 'CRM', status: 'andamento', agentId: 'aranha', priority: 'media' },
  { id: 't7', title: 'Auditar chamadas', category: 'OPS', status: 'andamento', priority: 'baixa' },
  { id: 't8', title: 'Email Abril', category: 'COPY', status: 'concluido', agentId: 'clow', priority: 'media' },
  { id: 't9', title: 'SEO Audit', category: 'SEO', status: 'concluido', agentId: 'lala', priority: 'alta' },
  { id: 't10', title: 'UTMs Setup', category: 'TRÁFEGO', status: 'concluido', agentId: 'finn', priority: 'baixa' },
  { id: 't11', title: 'Exportar rel. diário', category: 'DATA', status: 'concluido', agentId: 'aninha', priority: 'media' },
  { id: 't12', title: 'Validar contatos', category: 'CRM', status: 'concluido', agentId: 'aranha', priority: 'baixa' },
];

export const INITIAL_METRICS: Metrics = {
  agentsOnline: 8,
  activeTasks: 7,
  completedTasks: 35,
  tokensUsed: 284901,
};

export const LOG_MESSAGES = [
  (a: string) => `${a} iniciou análise de dados`,
  (a: string) => `${a} completou tarefa — 98% accuracy`,
  (a: string) => `${a} enviou relatório ao dashboard`,
  (a: string) => `${a} otimizou funil de conversão`,
  (a: string) => `${a} detectou anomalia nos leads`,
  (a: string) => `${a} gerou headline para campanha`,
  (a: string) => `${a} atualizou pipeline de vendas`,
  (a: string) => `${a} processou 47 registros`,
  (a: string) => `${a} validou integridade dos dados`,
  (a: string) => `${a} sincronizou CRM — 312 contatos`,
  (a: string) => `${a} pausou aguardando aprovação`,
  (a: string) => `${a} escalou ticket para humano`,
];

export const generateInitialLogs = (): LogEntry[] => {
  const agents = INITIAL_AGENTS.slice(0, 6);
  const now = new Date();
  return Array.from({ length: 12 }, (_, i) => {
    const agent = agents[i % agents.length];
    const d = new Date(now.getTime() - (12 - i) * 45000);
    return {
      id: `log-init-${i}`,
      time: d.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
      agentName: agent.name,
      agentEmoji: agent.emoji,
      message: LOG_MESSAGES[i % LOG_MESSAGES.length](agent.name),
    };
  });
};
